name: Stacksize
description: Modify the maximum stack sizes of materials.
version: 1.0.1
author: Torm
main: no.hyp.stacksize.Stacksize
api-version: 1.14

commands:
  stacksize:
    description: Modify or view the maximum stack size of a material.
    usage: /<command> <modify | view | inspect>

permissions:
  stacksize:
    description: All Stacksize permissions.
    default: op
    children: [stacksize.modify, stacksize.view]
  stacksize.modify:
    description: Modify maximum stack sizes.
    default: op
    children: [stacksize.view]
  stacksize.view:
    description: View and inspect maximum stack sizes.
    default: true
